const productData = {
  instagramImages: ["i1", "i2", "i3", "i4", "i5", "i6"],
  newType: ["YENİ! Kore", "Ramen"],
  types: [
    "Ramen",
    "Pizza",
    "Burger",
    "Kızartmalar",
    "Fast food",
    "Gazlı İçecekler",
  ],
  toppings: [
    "Pepperoni",
    "Sosis",
    "Kanada Jambonu",
    "Tavuk Izgara",
    "Sogan",
    "Domates",
    "Misir",
    "Sucuk",
    "Jalepeno",
    "Sarimsak",
    "Biber",
    "Ananas",
    "Kabak",
  ],
  size: [
    { value: "S", label: "S" },
    { value: "M", label: "M" },
    { value: "L", label: "L" },
  ],
  thickness: [
    { value: "İnce", label: "İnce" },
    { value: "Süpper İnce", label: "Süpper İnce" },
    { value: "Klasik", label: "Klasik" },
  ],
  initialFormData: {
    id: "",
    basePrice: 0,
    size: "",
    thickness: "",
    ingredients: [],
    amount: 1,
    name: "",
    note: "",
  },
  products: [
    {
      id: 1,
      name: "Spicy Tonkotsu Ramen",
      description:
        "Zengin tonkotsu çorbası ve baharatlı et dilimleriyle yapılan nefis ramen.",
      price: 390.9,
      rating: 4.8,
      reviewsCount: 180,
      type: "Ramen",
    },
    {
      id: 2,
      name: "Shoyu Ramen",
      description:
        "Soja bazlı hafif bir çorba ve tender et dilimleriyle servis edilen ramen.",
      price: 360.9,
      rating: 4.5,
      reviewsCount: 120,
      type: "Ramen",
    },
    {
      id: 3,
      name: "Miso Ramen",
      description:
        "Fermente miso çorbası ve taze malzemelerle zenginleştirilmiş ramen.",
      price: 320.9,
      rating: 4.7,
      reviewsCount: 150,
      type: "Ramen",
    },

    {
      id: 6,
      name: "Position Absolute Acı Pizza",
      description:
        "Frontent Dev olarak hala position:absolute kullanıyorsan bu çok acı pizza tam sana göre. Pizza, domates, peynir ve genellikle çeşitli diğer malzemelerle kaplanmış, daha sonra geleneksel olarak odun ateşinde bir fırında yüksek sıcaklıkta pişirilen, genellikle yuvarlak, düzleştirilmiş mayalı buğday bazlı hamurdan oluşan İtalyan kökenli lezzetli bir yemektir. . Küçük bir pizzaya bazen pizzetta denir.",
      price: 234.9,
      rating: 4.9,
      reviewsCount: 200,
      type: "Pizza",
    },
    {
      id: 9,
      name: "NPM Hızlı Pizza ",
      description:
        "Barbekü sosu, tavuk ve cheddar peyniri ile zenginleştirilmiş nefis bir pizza. Nihalin spesiyalidir",
      price: 249.9,
      rating: 4.8,
      reviewsCount: 200,
      type: "Pizza",
    },
    {
      id: 10,
      name: "Pizza Margherita",
      description:
        "Domates, mozzarella ve taze fesleğen ile hazırlanan klasik bir İtalyan pizzası.",
      price: 210.9,
      rating: 4.6,
      reviewsCount: 120,
      type: "Pizza",
    },

    {
      id: 13,
      name: "Veggie Burger",
      description:
        "Sebze tabanlı et yerine lezzetli ve sağlıklı bir veggie burger.",
      price: 293.9,
      rating: 4.3,
      reviewsCount: 150,
      type: "Burger",
    },
    {
      id: 14,
      name: "Double Cheeseburger",
      description:
        "İki kat et ve peynir ile yapılan doyurucu bir cheeseburger.",
      price: 420.9,
      rating: 4.6,
      reviewsCount: 130,
      type: "Burger",
    },
    {
      id: 15,
      name: "Hackathlon Burger",
      description:
        "Jalapeño biberleri ile acılı burger sevenler için mükemmel bir seçenek.",
      price: 290.9,
      rating: 4.4,
      reviewsCount: 110,
      type: "Burger",
    },

    {
      id: 16,
      name: "Classic French Fries",
      description: "Klasik kızarmış patates, çıtır çıtır ve lezzetli.",
      price: 105.9,
      rating: 4.8,
      reviewsCount: 200,
      type: "Kızartmalar",
    },
    {
      id: 17,
      name: "Sweet Potato Fries",
      description:
        "Tatlı patateslerden yapılan sağlıklı ve lezzetli kızartmalar.",
      price: 120.9,
      rating: 4.6,
      reviewsCount: 140,
      type: "Fast food",
    },
    {
      id: 18,
      name: "Garlic Parmesan Fries",
      description:
        "Sarımsak ve parmesan peynir ile lezzetlendirilmiş kızarmış patates.",
      price: 254.9,
      rating: 4.7,
      reviewsCount: 160,
      type: "Fast food",
    },
    {
      id: 19,
      name: "Curly Fries",
      description: "Çıtır ve eğlenceli şekliyle curly fries.",
      price: 149.9,
      rating: 4.4,
      reviewsCount: 120,
      type: "Kızartmalar",
    },
    {
      id: 20,
      name: "Chili Cheese Fries",
      description:
        "Baharatlı chili ve cheddar peynirle zenginleştirilmiş kızarmış patates.",
      price: 189.9,
      rating: 4.8,
      reviewsCount: 200,
      type: "Kızartmalar",
    },

    {
      id: 21,
      name: "Coca-Cola",
      description: "Dünyaca ünlü klasik gazlı içecek.",
      price: 75,
      rating: 4.9,
      reviewsCount: 300,
      type: "Gazlı İçecekler",
    },
    {
      id: 22,
      name: "Pepsi",
      description: "Bir başka klasik gazlı içecek seçeneği, Pepsi.",
      price: 75,
      rating: 4.6,
      reviewsCount: 220,
      type: "Gazlı İçecekler",
    },

    {
      id: 24,
      name: "Sprite",
      description: "Limonlu ve ferahlatıcı bir gazlı içecek.",
      price: 75,
      rating: 4.5,
      reviewsCount: 150,
      type: "Gazlı İçecekler",
    },
    {
      id: 25,
      name: "7UP",
      description: "Limonlu gazlı içecek, ferahlatıcı ve tatlı.",
      price: 75,
      rating: 4.4,
      reviewsCount: 140,
      type: "Fast food",
    },
    {
      id: 26,
      name: "Terminal Pizza",
      description: "Bol malzemeli özel tarif pizza.",
      price: 339.9,
      rating: 4.7,
      reviewsCount: 180,
      type: "Pizza",
    },
    {
      id: 27,
      name: "5 Kişilik Hackathlon Pizza",
      description: "5 kişilik büyük boy hackathlon pizza.",
      price: 690.5,
      rating: 4.9,
      reviewsCount: 250,
      type: "Pizza",
    },
    {
      id: 28,
      name: "useEffect Tavuklu Pizza",
      description: "Özel soslu tavuklu pizza.",
      price: 235.99,
      rating: 4.8,
      reviewsCount: 190,
      type: "Pizza",
    },
    {
      id: 29,
      name: "Beyaz Console Frosty",
      description: "Beyaz çikolatalı özel tatlı içecek.",
      price: 242.5,
      rating: 4.7,
      reviewsCount: 170,
      type: "Gazlı İçecekler",
    },
    {
      id: 30,
      name: "Testler Geçti Mutlu Burger",
      description: "Lezzetli ve doyurucu burger.",
      price: 237.99,
      rating: 4.8,
      reviewsCount: 180,
      type: "Burger",
    },
  ],
};

export default productData;
